version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: base
    container_name: server
    env_file:
      - ./.env
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 80:80
    networks:
      - back-tier
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: test
    ports:
    - "3314:3306"
    volumes:
    - "./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./mysql/insert.sql:/docker-entrypoint-initdb.d/2.sql"

    networks:
        - back-tier

volumes:
  mysql_data:
networks:
  back-tier:
