version: '3.7'
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks:
      - app
  web:
    restart: always
    container_name: web
    build: .
    depends_on:
      - nginx
    volumes:
      - ./:/var/www/
    networks:
      - app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
        - "./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - app
networks:
  app:
    driver: bridge


