version: '3'
services:
  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    networks:
      - app
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - web
    networks:
      - app
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
        - "./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - app
networks:
  app:
    driver: bridge


