CREATE DATABASE TEST_DATABASE;

USE TEST_DATABASE;

CREATE TABLE `TEST_DATABASE`.`TEST` (
  	`ID` bigint NOT NULL AUTO_INCREMENT,
  	`DESCRIPTION` varchar(100) DEFAULT NULL,
  	PRIMARY KEY (`ID`)
	);

CREATE TABLE `TEST_DATABASE`.`TEST_TWO` (
  	`ID` bigint NOT NULL AUTO_INCREMENT,
  	`DESCRIPTION` varchar(100) DEFAULT NULL,
  	PRIMARY KEY (`ID`)
	);