use TEST_DATABASE;
INSERT INTO TEST (DESCRIPTION) VALUES('SERVER OK');
INSERT INTO TEST (DESCRIPTION) VALUES('SERVER OK');
INSERT INTO TEST (DESCRIPTION) VALUES('SERVER OK');

INSERT INTO TEST_TWO (DESCRIPTION) VALUES('SERVER OK TWO');
INSERT INTO TEST_TWO (DESCRIPTION) VALUES('SERVER OK TWO' );
INSERT INTO TEST_TWO (DESCRIPTION) VALUES('SERVER OK TWO');

