version: '3.3'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: matheus
      MYSQL_PASSWORD: secret
  php-apache:
      depends_on: 
        - db
      container_name: php8-apache
      build: ./backend
      ports:
        - "8000:80"
      volumes:
        - ./backend/:/var/www/html
        - ./backend/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
        - ./backend/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
volumes:
  db_data: {}

