version: "3.1"
services:  

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    ports:
      - "8000:80"
    volumes:
      - .:/app
    working_dir: /app
  php-apache:
    image: php-backend-img
    container_name: php-backend
    depends_on:
    - db
    build: ./backend
    ports:
      - "8001:80"
    volumes:
      - ./backend/:/var/www/html
      - ./backend/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./backend/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini   
  db:
    image: mysql:5.7 
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql/insert.sql:/docker-entrypoint-initdb.d/2.sql"
  
     
  
  
