version: "3.1"
services:  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=teste
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - db-network
  php-apache:
    depends_on: 
    - db
    container_name: php8-apache
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/var/www/html
      - ./backend/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./backend/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini    
networks:
  db-network:
    driver: bridge
volumes:
  db:
    driver: local

      
  
  
  