version: "3.8"
services:
  php-apache:
    container_name: php8-apache
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/var/www/html
      - ./backend/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./backend/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ROOT_PASSWORD=teste
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local

      
  
  
  