version: "3.7"
services:  

  frontend:
    links:
    - php-apache
    
    container_name: frontend
    build: ./frontend
    ports:
      - "8159:80"
    volumes:
      - ./frontend:/frontend
      
    
  php-apache:
    restart: always
    container_name: php-apache
    depends_on:
    - db
    build: ./backend
    ports:
      - "8425:80"
    volumes:
      - ./backend/:/var/www/html
      - ./backend/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./backend/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini   
  db:
    image: mysql:5.7 
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3314:3306"
    volumes:
      - "./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql/insert.sql:/docker-entrypoint-initdb.d/2.sql"
  
     
  
  
