version: "3"
services:
  php-apache:
    container_name: php8-apache
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./backend/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./db:/var/lib/mysql"
  